name: "CD Pipeline"

on:
  workflow_run:
    workflows: ["CI Pipeline for ReactCICD"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: "Setup Node JS"
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: "Setup Vercel Cli"
        run: npm i -g vercel

      - name: "Download Build files"
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: "Deploy to vercel"
        run: vercel --prod --token=$VERCEL_TOKEN --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
