name: "CI Pipeline for ReactCICD"

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup Node JS"
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: "Check Node Version"
        run: node --version

      - name: "Clone The Reposiitory"
        uses: actions/checkout@v2

      - name: "Install Dependencies"
        run: npm install
